<script setup lang="ts">
import { useSnippetCreationStore } from "~~/stores/snippetCreationStore";
import { generateAvatar } from "~~/ts/utils";

const route = useRoute();

const { data, pending } = await useAsyncData("snippet", () =>
  $fetch(`/api/snippets/${route.params.id}`)
);

const copyCode = (code: string) => {
  navigator.clipboard.writeText(code);
};

const { frameworks } = useSnippetCreationStore();

const frameworkIcon = computed(
  () => frameworks.filter((f) => f.name == data.value?.framework)[0].icon
);

const codeLanguage = computed(() => {
  switch (data.value?.framework) {
    case "anchor":
      return "rust";
    case "seahorse":
      return "python";
    case "typescript":
      return "typescript";
    default:
      return "rust";
  }
});

const regex = /\${\d+:(.+?)}/g;
const prettyCode = computed(() => {
  if (!data.value?.code) return;
  const matches = data.value.code.matchAll(regex);
  for (const match of matches) {
    data.value.code = data.value?.code.replace(match[0], match[1]);
  }
  return data.value?.code;
});

const shortenCreatorAddress = (name: string) => {
  return `${name.slice(0, 4)}...${name.slice(-4)}`;
};

const formatDate = (milliseconds: number) => {
  const date = new Date(milliseconds);
  const options: Intl.DateTimeFormatOptions = {
    year: "2-digit",
    month: "2-digit",
    day: "2-digit",
  };
  return date.toLocaleDateString(undefined, options);
};
</script>

<template>
  <div class="pt-16 relative" v-if="!pending && data !== null">
    <div
      class="w-[12vw] fixed top-28 left-10 flex flex-col items-start justify-start border-r-2 border-white/10"
    >
      <div class="flex flex-row items-end justify-center space-x-3">
        <img
          :src="generateAvatar(data.creator)"
          alt=""
          class="h-6 w-6 rounded-sm"
        />
        <p class="text-white/60 text-sm">
          {{ shortenCreatorAddress(data.creator) }}
        </p>
      </div>

      <div
        class="mt-5 flex flex-row items-center justify-center space-x-3 text-white/60"
      >
        <icon name="line-md:heart-twotone" size="1.5em" />
        <p class="text-white/60 text-sm">{{ data.likes.length }}</p>
      </div>

      <div
        class="mt-3 flex flex-row items-center justify-center space-x-3 text-white/60"
      >
        <icon name="line-md:calendar" size="1.5em" />
        <p class="text-white/60 text-sm">{{ formatDate(data.createdAt) }}</p>
      </div>

      <div class="flex flex-wrap mt-5 text-white/60">
        <div
          v-for="tag in data.tags"
          :key="tag"
          class="px-2 py-1 mr-2 mb-2 bg-primary/10 rounded-sm text-xs"
        >
          {{ tag }}
        </div>
      </div>
    </div>

    <div
      class="w-[65vw] p-10 space-y-5 flex flex-col items-start justify-start left-1/2 -translate-x-1/2 absolute"
    >
      <div class="flex flex-row items-center justify-center space-x-3">
        <img :src="frameworkIcon" alt="" class="h-8 w-8" />
        <h3>{{ data.title }}</h3>
      </div>
      <p class="pb-2">{{ data.description }}</p>

      <div class="gradient-border w-full rounded-xl relative">
        <icon
          @click="copyCode(data!.code)"
          name="line-md:clipboard-check-twotone-to-clipboard-twotone-transition"
          size="1.4em"
          class="absolute right-2 top-2 z-10 cursor-pointer rounded-full text-primary/60 hover:text-primary/100 transition-all duration-300 active:text-secondary"
        />
        <prism :language="codeLanguage">{{ prettyCode }}</prism>
      </div>

      <div class="pt-10">
        <h4 class="ai-title">AI Generated Description</h4>
        <p>
          This description was generated by an AI model trained on thousands of
          lines of solana code.
        </p>
        <p class="mt-7 mb-5 py-3 px-4 border-[2px] border-white/10 rounded-xl">
          <span class="typewriter-effect" style="--n: 1000">
            {{ data.aiExplanation ?? "No explanation available at the moment" }}
          </span>
        </p>
        <div class="flex flex-row w-full space-x-3 grayscale">
          <input
            class="bg-background rounded-xl px-4 py-3 w-full border-white/10 border-[1.5px] text-base"
            type="text"
            placeholder="Ask Questions... (will be available soon)"
            disabled
          />
          <button
            class="bg-secondary/30 px-6 rounded-xl border-secondary border text-base"
            disabled
          >
            Send
          </button>
        </div>
      </div>
    </div>
  </div>
  <div v-else>Loading...</div>
</template>

<style lang="postcss" scoped>
.gradient-border {
  background: linear-gradient(
    200deg,
    rgb(var(--primary)),
    rgb(var(--secondary)),
    rgb(var(--primary)),
    rgb(var(--secondary))
  );
}

:not(pre) > code[class*="language-"],
pre[class*="language-"] {
  word-break: break-word;
  white-space: pre-wrap;
  @apply backdrop-blur-3xl bg-background m-[1px] rounded-2xl;
}

.typewriter-effect {
  color: transparent;
  background: linear-gradient(-90deg, #0000 0, #0000 5px) 10px 0,
    linear-gradient(white 0 0) 0 0;
  background-size: calc(var(--n) * 1ch) 200%;
  -webkit-background-clip: padding-box, text;
  background-clip: padding-box, text;
  background-repeat: no-repeat;
  animation: b 0.03s infinite steps(1),
    t calc(var(--n) * 0.03s) steps(var(--n)) forwards;
}
@keyframes t {
  from {
    background-size: 0 200%;
  }
}
@keyframes b {
  50% {
    background-position: 0 -100%, 0 0;
  }
}
</style>
