<script lang="ts">
  import type { Snippet } from "../types";
  import { onMount } from "svelte";
  import CodeField from "./CodeField.svelte";
  import HeartIcon from "../icons/HeartIcon.svelte";
  import { generateAvatar, getFrameworkIcon } from "../utils";
  import CalendarIcon from "../icons/CalendarIcon.svelte";
  import CopyIcon from "../icons/CopyIcon.svelte";
  import StarIcon from "../icons/StarIcon.svelte";
  import WandIcon from "../icons/WandIcon.svelte";
  import PinnedIcon from "../icons/PinnedIcon.svelte";

  // reactive snippet data
  let snippet: Snippet | null = null;

  // onMount(() => {
  window.addEventListener("message", (event) => {
    const { type, value }: { type: string; value: Snippet } = event.data;
    switch (type) {
      case "setSnippetData":
        snippet = value;
        break;
    }
  });
  // });

  const formatDate = (milliseconds: number) => {
    const date = new Date(milliseconds);
    const options: Intl.DateTimeFormatOptions = {
      year: "2-digit",
      month: "2-digit",
      day: "2-digit",
    };
    return date.toLocaleDateString(undefined, options);
  };

  const insertSnippet = () => {
    postMessage({
      type: "pinSnippet",
      value: snippet,
    });
  };

  const regex = /\${\d+:(.+?)}/g;
  const prettyCode = (code: string) => {
    const matches = code.matchAll(regex);
    for (const match of matches) {
      code = code.replace(match[0], match[1]);
    }
    return code;
  };
</script>

<div class="center-view">
  <div class="snippet-details-container">
    {#if snippet}
      <div class="left-container">
        <div class="title-container">
          <img
            class="snippet-framework-icon"
            src={getFrameworkIcon(snippet.framework)}
            alt={snippet.framework}
          />
          <h1 class="snippet-title">{snippet.title}</h1>
        </div>
        <p class="snippet-description">{snippet.description}</p>
        <CodeField
          code={prettyCode(snippet.code)}
          framework={snippet.framework}
        />

        <div class="ai-container">
          <h2 class="ai-title">AI Generated Description</h2>
          <p class="ai-description">
            This description was generated by an AI model trained on thousands
            of lines of solana code.
          </p>
          <p class="ai-answer" style="font-size: 13px;">
            <span class="typewriter-effect" style="--n: 1000;">
              {snippet.aiExplanation ??
                "No explanation available at the moment"}
            </span>
          </p>
          <div class="ai-input-container">
            <input
              class="ai-input"
              type="text"
              placeholder="Ask Questions... (will be available soon)"
              disabled
            />
            <button class="ai-input-button" disabled>Send</button>
          </div>
        </div>
      </div>

      <div class="right-container">
        <div class="creator-container">
          <img
            class="creator-avatar"
            src={generateAvatar(snippet.creator)}
            alt=""
          />
          <p class="creator-name">
            {snippet.creator.slice(0, 4) + "..." + snippet.creator.slice(-4)}
          </p>
        </div>
        <div class="likes-container">
          <HeartIcon />
          <p class="likes-count">21 Likes</p>
        </div>
        <div class="date-container">
          <CalendarIcon />
          <p class="date-text">{formatDate(snippet.createdAt)}</p>
        </div>
        <div class="snippet-tags-container">
          {#each snippet.tags as tag}
            <p class="snippet-tag">{tag}</p>
          {/each}
        </div>
        <div
          class="actions-container"
          style="margin-top:1rem; width:100%; display:flex; flex-direction: row;"
        >
          <button style="margin-right: 10px" on:click={insertSnippet}>
            <PinnedIcon />
          </button>

          <button>
            <StarIcon />
          </button>
        </div>
      </div>
    {/if}

    {#if !snippet}
      <p>Loading...</p>
    {/if}
  </div>
</div>

<svelte:head />

<style scoped>
  .snippet-details-container {
    max-width: 1000px;
    display: flex;
    flex-direction: row;
    align-items: start;
    justify-content: space-between;
    height: 100%;
    padding: 1.5rem;
  }
  .left-container {
    width: calc(100% - 230px);
    height: 100%;
    display: flex;
    flex-direction: column;
    align-items: start;
    justify-content: start;
  }
  .right-container {
    width: 180px;
    display: flex;
    flex-direction: column;
    align-items: start;
    justify-content: start;
    padding: 0.5rem 1rem;
    border-left: 1.5px solid var(--vscode-input-border);
  }
  .title-container {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: start;
    margin-bottom: 0.5rem;
  }
  .snippet-title {
    font-size: 1.5rem;
    font-weight: 600;
  }
  .snippet-framework-icon {
    width: 1.5rem;
    height: 1.5rem;
    margin-right: 0.5rem;
  }
  .snippet-description {
    font-weight: 400;
    margin-bottom: 1.5rem;
  }
  .creator-container {
    margin-bottom: 1rem;
    display: flex;
    flex-direction: row;
    align-items: center;
  }
  .creator-avatar {
    width: 20px;
    height: 20px;
    border-radius: 3px;
    margin-right: 0.5rem;
  }
  .creator-name {
    font-weight: 400;
  }
  .likes-container {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: start;
    margin-bottom: 0.5rem;
  }
  .likes-count {
    margin-left: 0.5rem;
    margin-bottom: 0.25px;
  }
  .date-container {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: start;
  }
  .date-text {
    margin-left: 0.5rem;
    margin-bottom: 0.25px;
  }
  .snippet-tags-container {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: start;
    margin-top: 1rem;
  }
  .snippet-tag {
    margin-right: 5px;
    margin-bottom: 5px;
    padding: 2px 5px;
    border-radius: 2px;
    background-color: var(--vscode-inputOption-activeBackground);
  }

  .ai-container {
    margin-top: 2rem;
    display: flex;
    flex-direction: column;
    align-items: start;
    justify-content: start;
  }
  .ai-title {
    font-size: 1.25rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
  }
  .ai-description {
    font-weight: 400;
    margin-bottom: 1rem;
  }
  .ai-answer {
    width: 100%;
    font-weight: 400;
    margin-bottom: 1rem;
    border: 2px solid var(--vscode-input-border);
    border-radius: 6px;
    padding: 0.5rem;
  }
  .ai-input-container {
    filter: grayscale(100%);
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: start;
    width: 100%;
  }
  .ai-input {
    width: 100%;
    height: 2rem;
    border: 0.5px solid var(--vscode-input-border);
    border-radius: 3px;
    padding: 0.25rem 0.5rem;
    font-size: 1rem;
    font-weight: 400;
    color: var(--vscode-input-foreground);
    background-color: var(--vscode-input-background);
  }
  .ai-input-button {
    width: 6rem;
    margin-left: 0.5rem;
    border-radius: 3px;
  }
  .typewriter-effect {
    color: transparent;
    background: linear-gradient(-90deg, #0000 0, #0000 5px) 10px 0,
      linear-gradient(var(--vscode-input-foreground) 0 0) 0 0;
    background-size: calc(var(--n) * 1ch) 200%;
    -webkit-background-clip: padding-box, text;
    background-clip: padding-box, text;
    background-repeat: no-repeat;
    animation: b 0.03s infinite steps(1),
      t calc(var(--n) * 0.03s) steps(var(--n)) forwards;
  }
  @keyframes t {
    from {
      background-size: 0 200%;
    }
  }
  @keyframes b {
    50% {
      background-position: 0 -100%, 0 0;
    }
  }
</style>
