# fly.toml app configuration file generated for cavyar on 2023-08-07T02:51:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cavyar"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

# [env]
#   BASE_URL="https://beta.cavyar.io"
#   AUTH_ORIGIN="https://beta.cavyar.io"
#   GITHUB_CLIENT_ID="9e3b2d8792738ffd589d"
